apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ticket-config
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.service.port }}"
  RABBITMQ_URL: "{{ .Values.config.rabbitmq_url }}"
  NOTIFICATION_SERVICE_URL: "{{ .Values.config.notification_service_url }}"