apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ticket
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ticket
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ticket
    spec:
      containers:
        - name: ticket-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-ticket-config
            - secretRef:
                name: {{ .Release.Name }}-ticket-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}