apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ticket
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-ticket
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-db
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: ticket-db
  ports:
    - port: {{ .Values.postgres.port }}