apiVersion: v1
kind: ConfigMap
metadata:
  name: events-config
  namespace: {{ .Values.nameSpace }}
data:
  PORT: {{ .Values.service.port | quote }}
  MONGO_HOST: {{ .Values.mongodb.host }}
  MONGO_PORT: {{ .Values.mongodb.port | quote }}
  MONGO_DB: {{ .Values.mongodb.database }}
  MONGO_URI: {{ .Values.mongodb.uri | quote }}