apiVersion: v1
kind: Secret
metadata:
  name: events-secret
  namespace: {{ .Values.nameSpace }}
type: Opaque
stringData:
  MONGO_USER: {{ .Values.mongodb.username }}
  MONGO_PASSWORD: {{ .Values.mongodb.password }}