global:
  namespace: team3-ns
  imagePullPolicy: IfNotPresent

  domain: api.gathergenie.in

  resources:
    defaultRequests:
      cpu: 100m
      memory: 128Mi
    defaultLimits:
      cpu: 500m
      memory: 512Mi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    cpu: 70


storageClass:
  name: team3-storageclass
  default: "true"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate

  nfs:
    server: 172.31.1.190 
    share: /mnt/nfs 

# ------------services-------------
admin:
  enabled: true
  replicaCount: 1
  image:
    repository: team3kubectl/admin-service
    tag: v1.1.1

ai:
  enabled: true
  replicaCount: 1
  image:
    repository: team3kubectl/ai-service
    tag: v1.1.1

booking:
  enabled: true
  replicaCount: 1
  image:
    repository: team3kubectl/booking-service
    tag: v1.1.1

events:
  enabled: true
  replicaCount: 1
  image:
    repository: team3kubectl/events-service
    tag: v1.1.1

frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: team3kubectl/frontend
    tag: v1.1.1
  
notification:
  enabled: true
  replicaCount: 1
  image:
    repository: team3kubectl/notification-service
    tag: v1.1.1

payment:
  enabled: true
  replicaCount: 1
  image:
    repository: team3kubectl/payment-microservice
    tag: v1.1.1

ticket:
  enabled: true
  replicaCount: 1
  image:
    repository: team3kubectl/ticket-service
    tag: v1.1.1

users:
  enabled: true
  replicaCount: 1
  image:
    repository: team3kubectl/users-service
    tag: v1.1.1