global:
  namespace: team3-ns
  imagePullPolicy: IfNotPresent

  domain: api.gathergenie.in

  resources:
    defaultRequests:
      cpu: 100m
      memory: 128Mi
    defaultLimits:
      cpu: 500m
      memory: 512Mi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    cpu: 70

storageClass:
  name: team3-storageclass
  default: "true"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate

  nfs:
    server: 172.31.1.190 
    share: /mnt/nfs 