apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
  namespace: {{ .Values.namespace }}

data:
  NODE_ENV: "{{ .Values.config.NODE_ENV }}"
  PORT: "{{ .Values.config.PORT }}"

  DB_HOST: "{{ .Values.config.DB_HOST }}"
  DB_PORT: "{{ .Values.config.DB_PORT }}"
  DB_NAME: "{{ .Values.config.DB_NAME }}"

  JWT_EXPIRES_IN: "{{ .Values.config.JWT_EXPIRES_IN }}"