service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 50


# Values imported from root during App of Apps transition
replicaCount: 1
image:
  repository: team3kubectl/frontend
  tag: v1.1.1
