
service:
  type: ClusterIP
  port: 80
  targetPort: 8006

config:
  PORT: "8006"
  REDIS_HOST: notification-redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"

secret:
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

serviceAccount:
  create: true
  name: notification-sa

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

livenessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 5
# Values imported from root during App of Apps transition
replicaCount: 1
image:
  repository: team3kubectl/notification-service
  tag: v1.1.1
