apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  RABBITMQ_USER: {{ .Values.secret.RABBITMQ_USER | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.secret.RABBITMQ_PASSWORD | b64enc }}