apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "{{ .Values.config.port }}"
  DB_HOST: "{{ .Values.config.dbHost }}"
  DB_PORT: "{{ .Values.config.dbPort }}"
  DB_NAME: "{{ .Values.config.dbName }}"
  EVENTS_SERVICE_URL: "{{ .Values.config.eventsServiceUrl }}"
  RABBITMQ_HOST: "{{ .Values.config.rabbitmqHost }}"
  RABBITMQ_PORT: "{{ .Values.config.rabbitmqPort }}"