apiVersion: v1
kind: Secret
metadata:
  name: booking-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.dbUser | b64enc }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc }}
  RABBITMQ_USER: {{ .Values.secret.rabbitmqUser | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.secret.rabbitmqPassword | b64enc }}