namespace: {{ .Release.Namespace }}

replicaCount: 1

image:
  repository: rabbitmq
  tag: 3-management
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  amqpPort: 5672
  managementPort: 15672

auth:
  username: guest
  password: guest

serviceAccount:
  create: true
  name: rabbitmq-sa

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5